// This file is @generated by prost-build.
/// 바둑, 오목 비트보드를 그대로 직렬화한 상태
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BadukBoardState {
    #[prost(fixed64, repeated, tag = "1")]
    pub black: ::prost::alloc::vec::Vec<u64>,
    #[prost(fixed64, repeated, tag = "2")]
    pub white: ::prost::alloc::vec::Vec<u64>,
}
/// * 플레이어 시간 정보
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlayerTimeInfo {
    #[prost(uint64, tag = "1")]
    pub main_time: u64,
    #[prost(uint64, tag = "2")]
    pub fischer_time: u64,
    #[prost(uint32, tag = "3")]
    pub remaining_overtime: u32,
    #[prost(uint64, tag = "4")]
    pub overtime: u64,
}
/// * 보드 시간 턴 정보
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GameState {
    #[prost(message, optional, tag = "1")]
    pub board: ::core::option::Option<BadukBoardState>,
    #[prost(message, optional, tag = "2")]
    pub black_time: ::core::option::Option<PlayerTimeInfo>,
    #[prost(message, optional, tag = "3")]
    pub white_time: ::core::option::Option<PlayerTimeInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChaksuRequest {
    #[prost(uint32, tag = "1")]
    pub coordinate: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DrawOfferRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResignRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassTurnRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GameStartRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientToServerRequest {
    #[prost(string, tag = "1")]
    pub session_key: ::prost::alloc::string::String,
    #[prost(
        oneof = "client_to_server_request::Payload",
        tags = "100, 101, 102, 103, 104"
    )]
    pub payload: ::core::option::Option<client_to_server_request::Payload>,
}
/// Nested message and enum types in `ClientToServerRequest`.
pub mod client_to_server_request {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "100")]
        Coordinate(super::ChaksuRequest),
        #[prost(message, tag = "101")]
        Resign(super::ResignRequest),
        #[prost(message, tag = "102")]
        DrawOffer(super::DrawOfferRequest),
        #[prost(message, tag = "103")]
        PassTurn(super::PassTurnRequest),
        #[prost(message, tag = "104")]
        Gamestart(super::GameStartRequest),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChaksuResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResignResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DrawOfferResponse {
    #[prost(string, tag = "1")]
    pub user_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassTurnResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfo {
    #[prost(string, tag = "1")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub rating: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GameStartResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UsersInfo {
    #[prost(message, optional, tag = "1")]
    pub black: ::core::option::Option<UserInfo>,
    #[prost(message, optional, tag = "2")]
    pub white: ::core::option::Option<UserInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerToClientResponse {
    #[prost(bool, tag = "1")]
    pub response_type: bool,
    #[prost(enumeration = "Color", tag = "2")]
    pub turn: i32,
    #[prost(enumeration = "Color", optional, tag = "3")]
    pub the_winner: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "4")]
    pub game_state: ::core::option::Option<GameState>,
    #[prost(message, optional, tag = "5")]
    pub users_info: ::core::option::Option<UsersInfo>,
    #[prost(
        oneof = "server_to_client_response::Payload",
        tags = "100, 101, 102, 103, 104"
    )]
    pub payload: ::core::option::Option<server_to_client_response::Payload>,
}
/// Nested message and enum types in `ServerToClientResponse`.
pub mod server_to_client_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "100")]
        Coordinate(super::ChaksuResponse),
        #[prost(message, tag = "101")]
        Resign(super::ResignResponse),
        #[prost(message, tag = "102")]
        DrawOffer(super::DrawOfferResponse),
        #[prost(message, tag = "103")]
        PassTurn(super::PassTurnResponse),
        #[prost(message, tag = "104")]
        GameStart(super::GameStartResponse),
    }
}
/// * 바둑판 턴 정보
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Color {
    Black = 0,
    White = 1,
    Free = 2,
    Error = 3,
}
impl Color {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Black => "COLOR_BLACK",
            Self::White => "COLOR_WHITE",
            Self::Free => "COLOR_FREE",
            Self::Error => "COLOR_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COLOR_BLACK" => Some(Self::Black),
            "COLOR_WHITE" => Some(Self::White),
            "COLOR_FREE" => Some(Self::Free),
            "COLOR_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
