/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GameListResponse,
  GameSgfResponse
} from '../../model';

import { customInstance } from '../../axios-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGameSgf = (
    gameId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GameSgfResponse>(
      {url: `/api/games/${gameId}/sgf`, method: 'GET', signal
    },
      options);
    }
  



export const getGetGameSgfQueryKey = (gameId?: number,) => {
    return [
    `/api/games/${gameId}/sgf`
    ] as const;
    }

    
export const getGetGameSgfQueryOptions = <TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameSgfQueryKey(gameId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameSgf>>> = ({ signal }) => getGameSgf(gameId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gameId),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameSgfQueryResult = NonNullable<Awaited<ReturnType<typeof getGameSgf>>>
export type GetGameSgfQueryError = void


export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameSgf>>,
          TError,
          Awaited<ReturnType<typeof getGameSgf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameSgf>>,
          TError,
          Awaited<ReturnType<typeof getGameSgf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameSgfQueryOptions(gameId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getMyGames = (
    sessionKey: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GameListResponse>(
      {url: `/api/user/games/session/${sessionKey}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyGamesQueryKey = (sessionKey?: string,) => {
    return [
    `/api/user/games/session/${sessionKey}`
    ] as const;
    }

    
export const getGetMyGamesQueryOptions = <TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyGamesQueryKey(sessionKey);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyGames>>> = ({ signal }) => getMyGames(sessionKey, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionKey),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyGamesQueryResult = NonNullable<Awaited<ReturnType<typeof getMyGames>>>
export type GetMyGamesQueryError = void


export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyGames>>,
          TError,
          Awaited<ReturnType<typeof getMyGames>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyGames>>,
          TError,
          Awaited<ReturnType<typeof getMyGames>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyGamesQueryOptions(sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




