/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  GameListResponse,
  GameSgfResponse
} from '../../model';


export const getGetGameSgfResponseMock = (overrideResponse: Partial< GameSgfResponse > = {}): GameSgfResponse => ({sgf: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetMyGamesResponseMock = (overrideResponse: Partial< GameListResponse > = {}): GameListResponse => ({games: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({board_size: faker.number.int({min: undefined, max: undefined}), created_at: faker.string.alpha({length: {min: 10, max: 20}}), game_type: faker.string.alpha({length: {min: 10, max: 20}}), id: faker.number.int({min: undefined, max: undefined}), my_color: faker.string.alpha({length: {min: 10, max: 20}}), opponent_id: faker.number.int({min: undefined, max: undefined}), result: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined])})), message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})


export const getGetGameSgfMockHandler = (overrideResponse?: GameSgfResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GameSgfResponse> | GameSgfResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/games/:gameId/sgf', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGameSgfResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetMyGamesMockHandler = (overrideResponse?: GameListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GameListResponse> | GameListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/games/session/:sessionKey', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyGamesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getGameMock = () => [
  getGetGameSgfMockHandler(),
  getGetMyGamesMockHandler()
]
