/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GameListResponse,
  GameSgfResponse
} from '../../model';

import { customInstance } from '../../axios-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getGameSgfResponse200 = {
  data: GameSgfResponse
  status: 200
}

export type getGameSgfResponse404 = {
  data: void
  status: 404
}

export type getGameSgfResponse500 = {
  data: void
  status: 500
}

export type getGameSgfResponseSuccess = (getGameSgfResponse200) & {
  headers: Headers;
};
export type getGameSgfResponseError = (getGameSgfResponse404 | getGameSgfResponse500) & {
  headers: Headers;
};

export type getGameSgfResponse = (getGameSgfResponseSuccess | getGameSgfResponseError)

export const getGetGameSgfUrl = (gameId: number,) => {




  return `/api/games/${gameId}/sgf`
}

export const getGameSgf = async (gameId: number, options?: RequestInit): Promise<getGameSgfResponse> => {

  return customInstance<getGameSgfResponse>(getGetGameSgfUrl(gameId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGameSgfQueryKey = (gameId: number,) => {
    return [
    `/api/games/${gameId}/sgf`
    ] as const;
    }


export const getGetGameSgfQueryOptions = <TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameSgfQueryKey(gameId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameSgf>>> = ({ signal }) => getGameSgf(gameId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: gameId !== null && gameId !== undefined,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameSgfQueryResult = NonNullable<Awaited<ReturnType<typeof getGameSgf>>>
export type GetGameSgfQueryError = void


export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameSgf>>,
          TError,
          Awaited<ReturnType<typeof getGameSgf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameSgf>>,
          TError,
          Awaited<ReturnType<typeof getGameSgf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameSgf<TData = Awaited<ReturnType<typeof getGameSgf>>, TError = void>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameSgf>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameSgfQueryOptions(gameId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getMyGamesResponse200 = {
  data: GameListResponse
  status: 200
}

export type getMyGamesResponse400 = {
  data: void
  status: 400
}

export type getMyGamesResponse500 = {
  data: void
  status: 500
}

export type getMyGamesResponseSuccess = (getMyGamesResponse200) & {
  headers: Headers;
};
export type getMyGamesResponseError = (getMyGamesResponse400 | getMyGamesResponse500) & {
  headers: Headers;
};

export type getMyGamesResponse = (getMyGamesResponseSuccess | getMyGamesResponseError)

export const getGetMyGamesUrl = (sessionKey: string,) => {




  return `/api/user/games/session/${sessionKey}`
}

export const getMyGames = async (sessionKey: string, options?: RequestInit): Promise<getMyGamesResponse> => {

  return customInstance<getMyGamesResponse>(getGetMyGamesUrl(sessionKey),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMyGamesQueryKey = (sessionKey: string,) => {
    return [
    `/api/user/games/session/${sessionKey}`
    ] as const;
    }


export const getGetMyGamesQueryOptions = <TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyGamesQueryKey(sessionKey);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyGames>>> = ({ signal }) => getMyGames(sessionKey, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: sessionKey !== null && sessionKey !== undefined,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyGamesQueryResult = NonNullable<Awaited<ReturnType<typeof getMyGames>>>
export type GetMyGamesQueryError = void


export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyGames>>,
          TError,
          Awaited<ReturnType<typeof getMyGames>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyGames>>,
          TError,
          Awaited<ReturnType<typeof getMyGames>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMyGames<TData = Awaited<ReturnType<typeof getMyGames>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyGamesQueryOptions(sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






