use std::io::{Result, Write};

const PROTO_DIR: &str = "assets/doljabiproto";
const OUT_DIR: &str = "src";

fn main() -> Result<()> {
    // `GENERATE_PROTO` 환경 변수가 설정되어 있을 때만 .proto 파일을 컴파일합니다.
    if std::env::var("GENERATE_PROTO").is_ok() {
        //println!("cargo:rerun-if-changed=assets/doljabiproto/"); // .proto 파일이 변경되면 다시 실행

        // 출력 디렉토리 생성
        std::fs::create_dir_all(OUT_DIR)?;

        // 폴더 내 모든 .proto 파일 경로 수집
        let proto_files: Vec<_> = std::fs::read_dir(PROTO_DIR)?
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                if path.extension()? == "proto" {
                    Some(path)
                } else {
                    None
                }
            })
            .collect();

        // .proto 파일명에서 모듈명 추출 (확장자 제거)
        let module_names: Vec<String> = proto_files
            .iter()
            .filter_map(|path| {
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .map(|s| s.to_string())
            })
            .collect();

        // prost로 .proto 파일 컴파일
        prost_build::Config::new()
            .out_dir(OUT_DIR)
            .compile_protos(&proto_files, &[PROTO_DIR])?;

        // mod.rs 파일 생성
        let lib_file_path = format!("{}/lib.rs", OUT_DIR);
        let mut lib_file = std::fs::File::create(&lib_file_path)?;

        writeln!(lib_file, "// This file is auto-generated by build.rs")?;
        writeln!(lib_file, "// Do not edit manually\n")?;

        for module_name in &module_names {
            writeln!(lib_file, "pub mod {};", module_name)?;
        }

        println!("cargo:rerun-if-changed={}/", PROTO_DIR);
        println!("Generated mod.rs with {} modules", module_names.len());
    }

    Ok(())
}
