/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  faker
} from '@faker-js/faker';

import type {
  CreateRoomResponseForm
} from '../../model';


export const getCreateRoomRequestResponseMock = (overrideResponse: Partial<Extract<CreateRoomResponseForm, object>> = {}): CreateRoomResponseForm => ({enter_code: faker.number.int({min: 0}), ...overrideResponse})

