/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateRoomResponseForm
} from '../../model';


export const getCreateRoomRequestResponseMock = (overrideResponse: Partial<Extract<CreateRoomResponseForm, object>> = {}): CreateRoomResponseForm => ({enter_code: faker.number.int({min: 0}), ...overrideResponse})


export const getCreateRoomRequestMockHandler = (overrideResponse?: CreateRoomResponseForm | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateRoomResponseForm> | CreateRoomResponseForm), options?: RequestHandlerOptions) => {
  return http.post('*/api/room/create', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateRoomRequestResponseMock(),
      { status: 201
      })
  }, options)
}

export const getEnterRoomMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.get('*/ws/room/:enterCode/session/:sessionKey', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getDefaultMock = () => [
  getCreateRoomRequestMockHandler(),
  getEnterRoomMockHandler()
]
