/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRoomRequestForm,
  CreateRoomResponseForm
} from '../../model';

import { customInstance } from '../../axios-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type createRoomRequestResponse201 = {
  data: CreateRoomResponseForm
  status: 201
}

export type createRoomRequestResponse400 = {
  data: void
  status: 400
}

export type createRoomRequestResponse500 = {
  data: void
  status: 500
}

export type createRoomRequestResponseSuccess = (createRoomRequestResponse201) & {
  headers: Headers;
};
export type createRoomRequestResponseError = (createRoomRequestResponse400 | createRoomRequestResponse500) & {
  headers: Headers;
};

export type createRoomRequestResponse = (createRoomRequestResponseSuccess | createRoomRequestResponseError)

export const getCreateRoomRequestUrl = () => {




  return `/api/room/create`
}

export const createRoomRequest = async (createRoomRequestForm: CreateRoomRequestForm, options?: RequestInit): Promise<createRoomRequestResponse> => {

  return customInstance<createRoomRequestResponse>(getCreateRoomRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRoomRequestForm)
  }
);}





export const getCreateRoomRequestQueryKey = (createRoomRequestForm?: CreateRoomRequestForm,) => {
    return [
    'POST', `/api/room/create`, createRoomRequestForm
    ] as const;
    }


export const getCreateRoomRequestQueryOptions = <TData = Awaited<ReturnType<typeof createRoomRequest>>, TError = void>(createRoomRequestForm: CreateRoomRequestForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateRoomRequestQueryKey(createRoomRequestForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createRoomRequest>>> = ({ signal }) => createRoomRequest(createRoomRequestForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateRoomRequestQueryResult = NonNullable<Awaited<ReturnType<typeof createRoomRequest>>>
export type CreateRoomRequestQueryError = void


export function useCreateRoomRequest<TData = Awaited<ReturnType<typeof createRoomRequest>>, TError = void>(
 createRoomRequestForm: CreateRoomRequestForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createRoomRequest>>,
          TError,
          Awaited<ReturnType<typeof createRoomRequest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateRoomRequest<TData = Awaited<ReturnType<typeof createRoomRequest>>, TError = void>(
 createRoomRequestForm: CreateRoomRequestForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createRoomRequest>>,
          TError,
          Awaited<ReturnType<typeof createRoomRequest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateRoomRequest<TData = Awaited<ReturnType<typeof createRoomRequest>>, TError = void>(
 createRoomRequestForm: CreateRoomRequestForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCreateRoomRequest<TData = Awaited<ReturnType<typeof createRoomRequest>>, TError = void>(
 createRoomRequestForm: CreateRoomRequestForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateRoomRequestQueryOptions(createRoomRequestForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type enterRoomResponse101 = {
  data: void
  status: 101
}

export type enterRoomResponse400 = {
  data: void
  status: 400
}

export type enterRoomResponse404 = {
  data: void
  status: 404
}

;
export type enterRoomResponseError = (enterRoomResponse101 | enterRoomResponse400 | enterRoomResponse404) & {
  headers: Headers;
};

export type enterRoomResponse = (enterRoomResponseError)

export const getEnterRoomUrl = (enterCode: number,
    sessionKey: string,) => {




  return `/ws/room/${enterCode}/session/${sessionKey}`
}

export const enterRoom = async (enterCode: number,
    sessionKey: string, options?: RequestInit): Promise<enterRoomResponse> => {

  return customInstance<enterRoomResponse>(getEnterRoomUrl(enterCode,sessionKey),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEnterRoomQueryKey = (enterCode: number,
    sessionKey: string,) => {
    return [
    `/ws/room/${enterCode}/session/${sessionKey}`
    ] as const;
    }


export const getEnterRoomQueryOptions = <TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnterRoomQueryKey(enterCode,sessionKey);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof enterRoom>>> = ({ signal }) => enterRoom(enterCode,sessionKey, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: enterCode !== null && enterCode !== undefined && sessionKey !== null && sessionKey !== undefined,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnterRoomQueryResult = NonNullable<Awaited<ReturnType<typeof enterRoom>>>
export type EnterRoomQueryError = void


export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enterRoom>>,
          TError,
          Awaited<ReturnType<typeof enterRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enterRoom>>,
          TError,
          Awaited<ReturnType<typeof enterRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnterRoomQueryOptions(enterCode,sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






