/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRoomRequestForm,
  CreateRoomResponseForm
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const createRoomRequest = (
    createRoomRequestForm: CreateRoomRequestForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateRoomResponseForm>(
      {url: `/api/room/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRoomRequestForm, signal
    },
      options);
    }
  


export const getCreateRoomRequestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError,{data: CreateRoomRequestForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError,{data: CreateRoomRequestForm}, TContext> => {

const mutationKey = ['createRoomRequest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRoomRequest>>, {data: CreateRoomRequestForm}> = (props) => {
          const {data} = props ?? {};

          return  createRoomRequest(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRoomRequestMutationResult = NonNullable<Awaited<ReturnType<typeof createRoomRequest>>>
    export type CreateRoomRequestMutationBody = CreateRoomRequestForm
    export type CreateRoomRequestMutationError = void

    export const useCreateRoomRequest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoomRequest>>, TError,{data: CreateRoomRequestForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRoomRequest>>,
        TError,
        {data: CreateRoomRequestForm},
        TContext
      > => {

      const mutationOptions = getCreateRoomRequestMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const enterRoom = (
    enterCode: number,
    sessionKey: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/ws/room/${enterCode}/session/${sessionKey}`, method: 'GET', signal
    },
      options);
    }
  



export const getEnterRoomQueryKey = (enterCode?: number,
    sessionKey?: string,) => {
    return [
    `/ws/room/${enterCode}/session/${sessionKey}`
    ] as const;
    }

    
export const getEnterRoomQueryOptions = <TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnterRoomQueryKey(enterCode,sessionKey);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof enterRoom>>> = ({ signal }) => enterRoom(enterCode,sessionKey, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(enterCode && sessionKey),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnterRoomQueryResult = NonNullable<Awaited<ReturnType<typeof enterRoom>>>
export type EnterRoomQueryError = void


export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enterRoom>>,
          TError,
          Awaited<ReturnType<typeof enterRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enterRoom>>,
          TError,
          Awaited<ReturnType<typeof enterRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEnterRoom<TData = Awaited<ReturnType<typeof enterRoom>>, TError = void>(
 enterCode: number,
    sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enterRoom>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnterRoomQueryOptions(enterCode,sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




