/*
 * doljabi
 *
 * doljabi project REST API를 정의한 문서입니다.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Login {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl Login {
    pub fn new(username: String, password: String) -> Login {
        Login {
            username,
            password,
        }
    }
}

