/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  LoginForm,
  LoginResponse,
  SessionCheckForm,
  SignupForm
} from '../../model';

import { customInstance } from '../../axios-instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type loginResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginResponse400 = {
  data: LoginResponse
  status: 400
}

export type loginResponse500 = {
  data: LoginResponse
  status: 500
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse400 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/api/login`
}

export const login = async (loginForm: LoginForm, options?: RequestInit): Promise<loginResponse> => {

  return customInstance<loginResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginForm)
  }
);}





export const getLoginQueryKey = (loginForm?: LoginForm,) => {
    return [
    'POST', `/api/login`, loginForm
    ] as const;
    }


export const getLoginQueryOptions = <TData = Awaited<ReturnType<typeof login>>, TError = LoginResponse>(loginForm: LoginForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginQueryKey(loginForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof login>>> = ({ signal }) => login(loginForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginQueryResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginQueryError = LoginResponse


export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = LoginResponse>(
 loginForm: LoginForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = LoginResponse>(
 loginForm: LoginForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = LoginResponse>(
 loginForm: LoginForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = LoginResponse>(
 loginForm: LoginForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginQueryOptions(loginForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type sessionCheckResponse200 = {
  data: void
  status: 200
}

export type sessionCheckResponse400 = {
  data: void
  status: 400
}

export type sessionCheckResponseSuccess = (sessionCheckResponse200) & {
  headers: Headers;
};
export type sessionCheckResponseError = (sessionCheckResponse400) & {
  headers: Headers;
};

export type sessionCheckResponse = (sessionCheckResponseSuccess | sessionCheckResponseError)

export const getSessionCheckUrl = () => {




  return `/api/session_check`
}

export const sessionCheck = async (sessionCheckForm: SessionCheckForm, options?: RequestInit): Promise<sessionCheckResponse> => {

  return customInstance<sessionCheckResponse>(getSessionCheckUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sessionCheckForm)
  }
);}





export const getSessionCheckQueryKey = (sessionCheckForm?: SessionCheckForm,) => {
    return [
    'POST', `/api/session_check`, sessionCheckForm
    ] as const;
    }


export const getSessionCheckQueryOptions = <TData = Awaited<ReturnType<typeof sessionCheck>>, TError = void>(sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSessionCheckQueryKey(sessionCheckForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionCheck>>> = ({ signal }) => sessionCheck(sessionCheckForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sessionCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SessionCheckQueryResult = NonNullable<Awaited<ReturnType<typeof sessionCheck>>>
export type SessionCheckQueryError = void


export function useSessionCheck<TData = Awaited<ReturnType<typeof sessionCheck>>, TError = void>(
 sessionCheckForm: SessionCheckForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionCheck>>,
          TError,
          Awaited<ReturnType<typeof sessionCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionCheck<TData = Awaited<ReturnType<typeof sessionCheck>>, TError = void>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionCheck>>,
          TError,
          Awaited<ReturnType<typeof sessionCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionCheck<TData = Awaited<ReturnType<typeof sessionCheck>>, TError = void>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSessionCheck<TData = Awaited<ReturnType<typeof sessionCheck>>, TError = void>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionCheck>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSessionCheckQueryOptions(sessionCheckForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type signupResponse201 = {
  data: ApiResponse
  status: 201
}

export type signupResponse400 = {
  data: ApiResponse
  status: 400
}

export type signupResponse500 = {
  data: ApiResponse
  status: 500
}

export type signupResponseSuccess = (signupResponse201) & {
  headers: Headers;
};
export type signupResponseError = (signupResponse400 | signupResponse500) & {
  headers: Headers;
};

export type signupResponse = (signupResponseSuccess | signupResponseError)

export const getSignupUrl = () => {




  return `/api/signup`
}

export const signup = async (signupForm: SignupForm, options?: RequestInit): Promise<signupResponse> => {

  return customInstance<signupResponse>(getSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signupForm)
  }
);}





export const getSignupQueryKey = (signupForm?: SignupForm,) => {
    return [
    'POST', `/api/signup`, signupForm
    ] as const;
    }


export const getSignupQueryOptions = <TData = Awaited<ReturnType<typeof signup>>, TError = ApiResponse>(signupForm: SignupForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSignupQueryKey(signupForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof signup>>> = ({ signal }) => signup(signupForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SignupQueryResult = NonNullable<Awaited<ReturnType<typeof signup>>>
export type SignupQueryError = ApiResponse


export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = ApiResponse>(
 signupForm: SignupForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signup>>,
          TError,
          Awaited<ReturnType<typeof signup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = ApiResponse>(
 signupForm: SignupForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signup>>,
          TError,
          Awaited<ReturnType<typeof signup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = ApiResponse>(
 signupForm: SignupForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = ApiResponse>(
 signupForm: SignupForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSignupQueryOptions(signupForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






