/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  faker
} from '@faker-js/faker';

import type {
  ApiResponse,
  LoginResponse
} from '../../model';


export const getLoginResponseMock = (overrideResponse: Partial<Extract<LoginResponse, object>> = {}): LoginResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), session_key: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), success: faker.datatype.boolean(), ...overrideResponse})

export const getSignupResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

