/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  LoginForm,
  LoginResponse,
  SessionCheckForm,
  SignupForm
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type loginResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginResponse400 = {
  data: LoginResponse
  status: 400
}

export type loginResponse500 = {
  data: LoginResponse
  status: 500
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse400 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `/api/login`
}

export const login = async (loginForm: LoginForm, options?: RequestInit): Promise<loginResponse> => {
  
  return customInstance<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginForm,)
  }
);}
  



export const getLoginMutationOptions = <TError = LoginResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginForm}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginForm}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginForm
    export type LoginMutationError = LoginResponse

    export const useLogin = <TError = LoginResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginForm},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    export type sessionCheckResponse200 = {
  data: void
  status: 200
}

export type sessionCheckResponse400 = {
  data: void
  status: 400
}

export type sessionCheckResponseSuccess = (sessionCheckResponse200) & {
  headers: Headers;
};
export type sessionCheckResponseError = (sessionCheckResponse400) & {
  headers: Headers;
};

export type sessionCheckResponse = (sessionCheckResponseSuccess | sessionCheckResponseError)

export const getSessionCheckUrl = () => {


  

  return `/api/session_check`
}

export const sessionCheck = async (sessionCheckForm: SessionCheckForm, options?: RequestInit): Promise<sessionCheckResponse> => {
  
  return customInstance<sessionCheckResponse>(getSessionCheckUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sessionCheckForm,)
  }
);}
  



export const getSessionCheckMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionCheck>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sessionCheck>>, TError,{data: SessionCheckForm}, TContext> => {

const mutationKey = ['sessionCheck'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionCheck>>, {data: SessionCheckForm}> = (props) => {
          const {data} = props ?? {};

          return  sessionCheck(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SessionCheckMutationResult = NonNullable<Awaited<ReturnType<typeof sessionCheck>>>
    export type SessionCheckMutationBody = SessionCheckForm
    export type SessionCheckMutationError = void

    export const useSessionCheck = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionCheck>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sessionCheck>>,
        TError,
        {data: SessionCheckForm},
        TContext
      > => {
      return useMutation(getSessionCheckMutationOptions(options), queryClient);
    }
    export type signupResponse201 = {
  data: ApiResponse
  status: 201
}

export type signupResponse400 = {
  data: ApiResponse
  status: 400
}

export type signupResponse500 = {
  data: ApiResponse
  status: 500
}

export type signupResponseSuccess = (signupResponse201) & {
  headers: Headers;
};
export type signupResponseError = (signupResponse400 | signupResponse500) & {
  headers: Headers;
};

export type signupResponse = (signupResponseSuccess | signupResponseError)

export const getSignupUrl = () => {


  

  return `/api/signup`
}

export const signup = async (signupForm: SignupForm, options?: RequestInit): Promise<signupResponse> => {
  
  return customInstance<signupResponse>(getSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupForm,)
  }
);}
  



export const getSignupMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupForm}, TContext> => {

const mutationKey = ['signup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, {data: SignupForm}> = (props) => {
          const {data} = props ?? {};

          return  signup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
    export type SignupMutationBody = SignupForm
    export type SignupMutationError = ApiResponse

    export const useSignup = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: SignupForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signup>>,
        TError,
        {data: SignupForm},
        TContext
      > => {
      return useMutation(getSignupMutationOptions(options), queryClient);
    }
    