/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type CreateRoomRequestFormOneOfThreeGameType = typeof CreateRoomRequestFormOneOfThreeGameType[keyof typeof CreateRoomRequestFormOneOfThreeGameType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoomRequestFormOneOfThreeGameType = {
  omok: 'omok',
} as const;
