/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { BadukBoardGameConfig } from './badukBoardGameConfig';

export type CreateRoomRequestForm = {
  game_config: BadukBoardGameConfig;
  game_type: 'baduk';
} | {
  game_config: BadukBoardGameConfig;
  game_type: 'omok';
};
