/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import type { BadukBoardGameConfig } from './badukBoardGameConfig';

export type CreateRoomRequestForm = {
  game_config: BadukBoardGameConfig;
  game_type: 'baduk';
} | {
  game_config: BadukBoardGameConfig;
  game_type: 'omok';
};
