/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.4
 */
import type { CreateRoomRequestFormOneOf } from './createRoomRequestFormOneOf';
import type { CreateRoomRequestFormOneOfThree } from './createRoomRequestFormOneOfThree';

export type CreateRoomRequestForm = CreateRoomRequestFormOneOf | CreateRoomRequestFormOneOfThree;
