/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import type { BadukBoardGameConfig } from './badukBoardGameConfig';
import type { CreateRoomRequestFormOneOfGameType } from './createRoomRequestFormOneOfGameType';

export type CreateRoomRequestFormOneOf = {
  game_config: BadukBoardGameConfig;
  game_type: CreateRoomRequestFormOneOfGameType;
};
