/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import type { GameSummaryResult } from './gameSummaryResult';

export interface GameSummary {
  board_size: number;
  created_at: string;
  /** "baduk" | "omok" */
  game_type: string;
  id: number;
  /** 요청자가 둔 색 ("black" | "white") */
  my_color: string;
  /** 요청자 입장에서 상대 플레이어의 user_id */
  opponent_id: number;
  /** SGF RE[] 형식 ("B+R", "W+T", "B+5", "Draw"). 미정이면 null */
  result?: GameSummaryResult;
}
