/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.4
 */

export type GetMyGamesParams = {
/**
 * 게임 종류 필터: "baduk" | "omok". 생략 시 전체 반환
 */
game_type?: string;
};
