/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponseSessionKey } from './loginResponseSessionKey';

export interface LoginResponse {
  message: string;
  session_key?: LoginResponseSessionKey;
  success: boolean;
}
