/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface SignupForm {
  /** 로그인에 사용할 아이디 */
  login_id: string;
  /** 평문 비밀번호 */
  password: string;
  /** 사용자 이름 (닉네임) */
  username: string;
}
