/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfile } from './userProfile';

export interface UserProfileResponse {
  message: string;
  success: boolean;
  user?: null | UserProfile;
}
