/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */

export interface UserProfile {
  rating: number;
  /** @nullable */
  username?: string | null;
}
