/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 0.2.3
 */
import {
  faker
} from '@faker-js/faker';

import type {
  ApiResponse,
  GameResultInformationFrom,
  UserProfile,
  UserProfileResponse
} from '../../model';


export const getDeleteUserResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

export const getGetGameResultResponseMock = (overrideResponse: Partial<Extract<GameResultInformationFrom, object>> = {}): GameResultInformationFrom => ({draw: faker.number.int(), lose: faker.number.int(), win: faker.number.int(), ...overrideResponse})

export const getGetUserProfileHandlerResponseUserProfileMock = (overrideResponse: Partial<UserProfile> = {}): UserProfile => ({...{rating: faker.number.int(), username: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])}, ...overrideResponse});

export const getGetUserProfileHandlerResponseMock = (overrideResponse: Partial<Extract<UserProfileResponse, object>> = {}): UserProfileResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), user: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetUserProfileHandlerResponseUserProfileMock()},]), undefined]), ...overrideResponse})

export const getUpdatePasswordResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

export const getUpdateUsernameResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

