/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  GameResultInformationFrom,
  SessionCheckForm,
  UpdatePasswordForm,
  UpdateUsernameForm,
  UserProfileResponse
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type deleteUserResponse200 = {
  data: ApiResponse
  status: 200
}

export type deleteUserResponse400 = {
  data: ApiResponse
  status: 400
}

export type deleteUserResponse500 = {
  data: ApiResponse
  status: 500
}

export type deleteUserResponseSuccess = (deleteUserResponse200) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse400 | deleteUserResponse500) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = () => {


  

  return `/api/user/delete`
}

export const deleteUser = async (sessionCheckForm: SessionCheckForm, options?: RequestInit): Promise<deleteUserResponse> => {
  
  return customInstance<deleteUserResponse>(getDeleteUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sessionCheckForm,)
  }
);}
  



export const getDeleteUserMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: SessionCheckForm}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {data: SessionCheckForm}> = (props) => {
          const {data} = props ?? {};

          return  deleteUser(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    export type DeleteUserMutationBody = SessionCheckForm
    export type DeleteUserMutationError = ApiResponse

    export const useDeleteUser = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {data: SessionCheckForm},
        TContext
      > => {
      return useMutation(getDeleteUserMutationOptions(options), queryClient);
    }
    export type getGameResultResponse200 = {
  data: GameResultInformationFrom
  status: 200
}

export type getGameResultResponse400 = {
  data: void
  status: 400
}

export type getGameResultResponse404 = {
  data: void
  status: 404
}

export type getGameResultResponse500 = {
  data: void
  status: 500
}

export type getGameResultResponseSuccess = (getGameResultResponse200) & {
  headers: Headers;
};
export type getGameResultResponseError = (getGameResultResponse400 | getGameResultResponse404 | getGameResultResponse500) & {
  headers: Headers;
};

export type getGameResultResponse = (getGameResultResponseSuccess | getGameResultResponseError)

export const getGetGameResultUrl = (sessionKey: string,) => {


  

  return `/api/user/game_result_info/session/${sessionKey}`
}

export const getGameResult = async (sessionKey: string, options?: RequestInit): Promise<getGameResultResponse> => {
  
  return customInstance<getGameResultResponse>(getGetGameResultUrl(sessionKey),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetGameResultQueryKey = (sessionKey: string,) => {
    return [
    `/api/user/game_result_info/session/${sessionKey}`
    ] as const;
    }

    
export const getGetGameResultQueryOptions = <TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameResultQueryKey(sessionKey);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameResult>>> = ({ signal }) => getGameResult(sessionKey, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(sessionKey),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameResultQueryResult = NonNullable<Awaited<ReturnType<typeof getGameResult>>>
export type GetGameResultQueryError = void


export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameResult>>,
          TError,
          Awaited<ReturnType<typeof getGameResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameResult>>,
          TError,
          Awaited<ReturnType<typeof getGameResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameResultQueryOptions(sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type getUserProfileHandlerResponse200 = {
  data: UserProfileResponse
  status: 200
}

export type getUserProfileHandlerResponse404 = {
  data: UserProfileResponse
  status: 404
}

export type getUserProfileHandlerResponse500 = {
  data: UserProfileResponse
  status: 500
}

export type getUserProfileHandlerResponseSuccess = (getUserProfileHandlerResponse200) & {
  headers: Headers;
};
export type getUserProfileHandlerResponseError = (getUserProfileHandlerResponse404 | getUserProfileHandlerResponse500) & {
  headers: Headers;
};

export type getUserProfileHandlerResponse = (getUserProfileHandlerResponseSuccess | getUserProfileHandlerResponseError)

export const getGetUserProfileHandlerUrl = () => {


  

  return `/api/user/profile`
}

export const getUserProfileHandler = async (sessionCheckForm: SessionCheckForm, options?: RequestInit): Promise<getUserProfileHandlerResponse> => {
  
  return customInstance<getUserProfileHandlerResponse>(getGetUserProfileHandlerUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      sessionCheckForm,)
  }
);}
  



export const getGetUserProfileHandlerMutationOptions = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext> => {

const mutationKey = ['getUserProfileHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserProfileHandler>>, {data: SessionCheckForm}> = (props) => {
          const {data} = props ?? {};

          return  getUserProfileHandler(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetUserProfileHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof getUserProfileHandler>>>
    export type GetUserProfileHandlerMutationBody = SessionCheckForm
    export type GetUserProfileHandlerMutationError = UserProfileResponse

    export const useGetUserProfileHandler = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUserProfileHandler>>,
        TError,
        {data: SessionCheckForm},
        TContext
      > => {
      return useMutation(getGetUserProfileHandlerMutationOptions(options), queryClient);
    }
    export type updatePasswordResponse200 = {
  data: ApiResponse
  status: 200
}

export type updatePasswordResponse400 = {
  data: ApiResponse
  status: 400
}

export type updatePasswordResponse500 = {
  data: ApiResponse
  status: 500
}

export type updatePasswordResponseSuccess = (updatePasswordResponse200) & {
  headers: Headers;
};
export type updatePasswordResponseError = (updatePasswordResponse400 | updatePasswordResponse500) & {
  headers: Headers;
};

export type updatePasswordResponse = (updatePasswordResponseSuccess | updatePasswordResponseError)

export const getUpdatePasswordUrl = () => {


  

  return `/api/user/update-password`
}

export const updatePassword = async (updatePasswordForm: UpdatePasswordForm, options?: RequestInit): Promise<updatePasswordResponse> => {
  
  return customInstance<updatePasswordResponse>(getUpdatePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePasswordForm,)
  }
);}
  



export const getUpdatePasswordMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext> => {

const mutationKey = ['updatePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePassword>>, {data: UpdatePasswordForm}> = (props) => {
          const {data} = props ?? {};

          return  updatePassword(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
    export type UpdatePasswordMutationBody = UpdatePasswordForm
    export type UpdatePasswordMutationError = ApiResponse

    export const useUpdatePassword = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePassword>>,
        TError,
        {data: UpdatePasswordForm},
        TContext
      > => {
      return useMutation(getUpdatePasswordMutationOptions(options), queryClient);
    }
    export type updateUsernameResponse200 = {
  data: ApiResponse
  status: 200
}

export type updateUsernameResponse400 = {
  data: ApiResponse
  status: 400
}

export type updateUsernameResponse500 = {
  data: ApiResponse
  status: 500
}

export type updateUsernameResponseSuccess = (updateUsernameResponse200) & {
  headers: Headers;
};
export type updateUsernameResponseError = (updateUsernameResponse400 | updateUsernameResponse500) & {
  headers: Headers;
};

export type updateUsernameResponse = (updateUsernameResponseSuccess | updateUsernameResponseError)

export const getUpdateUsernameUrl = () => {


  

  return `/api/user/update-username`
}

export const updateUsername = async (updateUsernameForm: UpdateUsernameForm, options?: RequestInit): Promise<updateUsernameResponse> => {
  
  return customInstance<updateUsernameResponse>(getUpdateUsernameUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUsernameForm,)
  }
);}
  



export const getUpdateUsernameMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext> => {

const mutationKey = ['updateUsername'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUsername>>, {data: UpdateUsernameForm}> = (props) => {
          const {data} = props ?? {};

          return  updateUsername(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof updateUsername>>>
    export type UpdateUsernameMutationBody = UpdateUsernameForm
    export type UpdateUsernameMutationError = ApiResponse

    export const useUpdateUsername = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUsername>>,
        TError,
        {data: UpdateUsernameForm},
        TContext
      > => {
      return useMutation(getUpdateUsernameMutationOptions(options), queryClient);
    }
    