/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiResponse,
  GameResultInformationFrom,
  UserProfile,
  UserProfileResponse
} from '../../model';


export const getDeleteUserResponseMock = (overrideResponse: Partial< ApiResponse > = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

export const getGetGameResultResponseMock = (overrideResponse: Partial< GameResultInformationFrom > = {}): GameResultInformationFrom => ({draw: faker.number.int({min: undefined, max: undefined}), lose: faker.number.int({min: undefined, max: undefined}), win: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetUserProfileHandlerResponseUserProfileMock = (overrideResponse: Partial<UserProfile> = {}): UserProfile => ({...{rating: faker.number.int({min: undefined, max: undefined}), username: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined])}, ...overrideResponse});

export const getGetUserProfileHandlerResponseMock = (overrideResponse: Partial< UserProfileResponse > = {}): UserProfileResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), user: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetUserProfileHandlerResponseUserProfileMock()},]), undefined]), ...overrideResponse})

export const getUpdatePasswordResponseMock = (overrideResponse: Partial< ApiResponse > = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

export const getUpdateUsernameResponseMock = (overrideResponse: Partial< ApiResponse > = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})


export const getDeleteUserMockHandler = (overrideResponse?: ApiResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponse> | ApiResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/delete', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetGameResultMockHandler = (overrideResponse?: GameResultInformationFrom | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GameResultInformationFrom> | GameResultInformationFrom), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/game_result_info/session/:sessionKey', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGameResultResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetUserProfileHandlerMockHandler = (overrideResponse?: UserProfileResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserProfileResponse> | UserProfileResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserProfileHandlerResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdatePasswordMockHandler = (overrideResponse?: ApiResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponse> | ApiResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/update-password', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdatePasswordResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateUsernameMockHandler = (overrideResponse?: ApiResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponse> | ApiResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/update-username', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateUsernameResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUserMock = () => [
  getDeleteUserMockHandler(),
  getGetGameResultMockHandler(),
  getGetUserProfileHandlerMockHandler(),
  getUpdatePasswordMockHandler(),
  getUpdateUsernameMockHandler()
]
