/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  GameResultInformationFrom,
  SessionCheckForm,
  UpdatePasswordForm,
  UpdateUsernameForm,
  UserProfileResponse
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const deleteUser = (
    sessionCheckForm: SessionCheckForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/api/user/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionCheckForm, signal
    },
      options);
    }
  


export const getDeleteUserMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: SessionCheckForm}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {data: SessionCheckForm}> = (props) => {
          const {data} = props ?? {};

          return  deleteUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    export type DeleteUserMutationBody = SessionCheckForm
    export type DeleteUserMutationError = ApiResponse

    export const useDeleteUser = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {data: SessionCheckForm},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getGameResult = (
    sessionKey: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GameResultInformationFrom>(
      {url: `/api/user/game_result_info/session/${sessionKey}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetGameResultQueryKey = (sessionKey?: string,) => {
    return [
    `/api/user/game_result_info/session/${sessionKey}`
    ] as const;
    }

    
export const getGetGameResultQueryOptions = <TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameResultQueryKey(sessionKey);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameResult>>> = ({ signal }) => getGameResult(sessionKey, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionKey),  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameResultQueryResult = NonNullable<Awaited<ReturnType<typeof getGameResult>>>
export type GetGameResultQueryError = void


export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameResult>>,
          TError,
          Awaited<ReturnType<typeof getGameResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameResult>>,
          TError,
          Awaited<ReturnType<typeof getGameResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameResultQueryOptions(sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getUserProfileHandler = (
    sessionCheckForm: SessionCheckForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserProfileResponse>(
      {url: `/api/user/profile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionCheckForm, signal
    },
      options);
    }
  


export const getGetUserProfileHandlerMutationOptions = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext> => {

const mutationKey = ['getUserProfileHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserProfileHandler>>, {data: SessionCheckForm}> = (props) => {
          const {data} = props ?? {};

          return  getUserProfileHandler(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetUserProfileHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof getUserProfileHandler>>>
    export type GetUserProfileHandlerMutationBody = SessionCheckForm
    export type GetUserProfileHandlerMutationError = UserProfileResponse

    export const useGetUserProfileHandler = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUserProfileHandler>>,
        TError,
        {data: SessionCheckForm},
        TContext
      > => {

      const mutationOptions = getGetUserProfileHandlerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updatePassword = (
    updatePasswordForm: UpdatePasswordForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/api/user/update-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updatePasswordForm, signal
    },
      options);
    }
  


export const getUpdatePasswordMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext> => {

const mutationKey = ['updatePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePassword>>, {data: UpdatePasswordForm}> = (props) => {
          const {data} = props ?? {};

          return  updatePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
    export type UpdatePasswordMutationBody = UpdatePasswordForm
    export type UpdatePasswordMutationError = ApiResponse

    export const useUpdatePassword = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePassword>>,
        TError,
        {data: UpdatePasswordForm},
        TContext
      > => {

      const mutationOptions = getUpdatePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateUsername = (
    updateUsernameForm: UpdateUsernameForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/api/user/update-username`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUsernameForm, signal
    },
      options);
    }
  


export const getUpdateUsernameMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext> => {

const mutationKey = ['updateUsername'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUsername>>, {data: UpdateUsernameForm}> = (props) => {
          const {data} = props ?? {};

          return  updateUsername(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof updateUsername>>>
    export type UpdateUsernameMutationBody = UpdateUsernameForm
    export type UpdateUsernameMutationError = ApiResponse

    export const useUpdateUsername = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUsername>>,
        TError,
        {data: UpdateUsernameForm},
        TContext
      > => {

      const mutationOptions = getUpdateUsernameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    