/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  SessionCheckForm,
  UpdatePasswordForm,
  UpdateUsernameForm,
  UserProfileResponse
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUserProfileHandler = (
    sessionCheckForm: SessionCheckForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserProfileResponse>(
      {url: `/api/user/profile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionCheckForm, signal
    },
      options);
    }
  


export const getGetUserProfileHandlerMutationOptions = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext> => {

const mutationKey = ['getUserProfileHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserProfileHandler>>, {data: SessionCheckForm}> = (props) => {
          const {data} = props ?? {};

          return  getUserProfileHandler(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetUserProfileHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof getUserProfileHandler>>>
    export type GetUserProfileHandlerMutationBody = SessionCheckForm
    export type GetUserProfileHandlerMutationError = UserProfileResponse

    export const useGetUserProfileHandler = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: SessionCheckForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUserProfileHandler>>,
        TError,
        {data: SessionCheckForm},
        TContext
      > => {

      const mutationOptions = getGetUserProfileHandlerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updatePassword = (
    updatePasswordForm: UpdatePasswordForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/api/user/update-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updatePasswordForm, signal
    },
      options);
    }
  


export const getUpdatePasswordMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext> => {

const mutationKey = ['updatePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePassword>>, {data: UpdatePasswordForm}> = (props) => {
          const {data} = props ?? {};

          return  updatePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
    export type UpdatePasswordMutationBody = UpdatePasswordForm
    export type UpdatePasswordMutationError = ApiResponse

    export const useUpdatePassword = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePassword>>, TError,{data: UpdatePasswordForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePassword>>,
        TError,
        {data: UpdatePasswordForm},
        TContext
      > => {

      const mutationOptions = getUpdatePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const updateUsername = (
    updateUsernameForm: UpdateUsernameForm,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiResponse>(
      {url: `/api/user/update-username`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateUsernameForm, signal
    },
      options);
    }
  


export const getUpdateUsernameMutationOptions = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext> => {

const mutationKey = ['updateUsername'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUsername>>, {data: UpdateUsernameForm}> = (props) => {
          const {data} = props ?? {};

          return  updateUsername(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof updateUsername>>>
    export type UpdateUsernameMutationBody = UpdateUsernameForm
    export type UpdateUsernameMutationError = ApiResponse

    export const useUpdateUsername = <TError = ApiResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUsername>>, TError,{data: UpdateUsernameForm}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUsername>>,
        TError,
        {data: UpdateUsernameForm},
        TContext
      > => {

      const mutationOptions = getUpdateUsernameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    