/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiResponse,
  GameResultInformationFrom,
  UserProfile,
  UserProfileResponse
} from '../../model';


export const getDeleteUserResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

export const getGetGameResultResponseMock = (overrideResponse: Partial<Extract<GameResultInformationFrom, object>> = {}): GameResultInformationFrom => ({draw: faker.number.int(), lose: faker.number.int(), win: faker.number.int(), ...overrideResponse})

export const getGetUserProfileHandlerResponseUserProfileMock = (overrideResponse: Partial<UserProfile> = {}): UserProfile => ({...{rating: faker.number.int(), username: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])}, ...overrideResponse});

export const getGetUserProfileHandlerResponseMock = (overrideResponse: Partial<Extract<UserProfileResponse, object>> = {}): UserProfileResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), user: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetUserProfileHandlerResponseUserProfileMock()},]), undefined]), ...overrideResponse})

export const getUpdatePasswordResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})

export const getUpdateUsernameResponseMock = (overrideResponse: Partial<Extract<ApiResponse, object>> = {}): ApiResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), ...overrideResponse})


export const getDeleteUserMockHandler = (overrideResponse?: ApiResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponse> | ApiResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/delete', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteUserResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetGameResultMockHandler = (overrideResponse?: GameResultInformationFrom | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GameResultInformationFrom> | GameResultInformationFrom), options?: RequestHandlerOptions) => {
  return http.get('*/api/user/game_result_info/session/:sessionKey', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGameResultResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetUserProfileHandlerMockHandler = (overrideResponse?: UserProfileResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserProfileResponse> | UserProfileResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/profile', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserProfileHandlerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdatePasswordMockHandler = (overrideResponse?: ApiResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponse> | ApiResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/update-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdatePasswordResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateUsernameMockHandler = (overrideResponse?: ApiResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponse> | ApiResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/update-username', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateUsernameResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserMock = () => [
  getDeleteUserMockHandler(),
  getGetGameResultMockHandler(),
  getGetUserProfileHandlerMockHandler(),
  getUpdatePasswordMockHandler(),
  getUpdateUsernameMockHandler()
]
