/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileUsername } from './userProfileUsername';

export interface UserProfile {
  /** @minimum 0 */
  id: number;
  login_id: string;
  rating: number;
  username?: UserProfileUsername;
}
