/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UserProfileRequest,
  UserProfileResponse
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getUserProfileHandler = (
    userProfileRequest: UserProfileRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserProfileResponse>(
      {url: `/api/user/profile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userProfileRequest, signal
    },
      options);
    }
  


export const getGetUserProfileHandlerMutationOptions = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: UserProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: UserProfileRequest}, TContext> => {

const mutationKey = ['getUserProfileHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserProfileHandler>>, {data: UserProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  getUserProfileHandler(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetUserProfileHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof getUserProfileHandler>>>
    export type GetUserProfileHandlerMutationBody = UserProfileRequest
    export type GetUserProfileHandlerMutationError = UserProfileResponse

    export const useGetUserProfileHandler = <TError = UserProfileResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError,{data: UserProfileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUserProfileHandler>>,
        TError,
        {data: UserProfileRequest},
        TContext
      > => {

      const mutationOptions = getGetUserProfileHandlerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    