/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  UserProfile,
  UserProfileResponse
} from '../../model';


export const getGetUserProfileHandlerResponseUserProfileMock = (overrideResponse: Partial<UserProfile> = {}): UserProfile => ({...{id: faker.number.int({min: 0, max: undefined}), login_id: faker.string.alpha({length: {min: 10, max: 20}}), rating: faker.number.int({min: undefined, max: undefined}), username: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), undefined])}, ...overrideResponse});

export const getGetUserProfileHandlerResponseMock = (overrideResponse: Partial< UserProfileResponse > = {}): UserProfileResponse => ({message: faker.string.alpha({length: {min: 10, max: 20}}), success: faker.datatype.boolean(), user: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetUserProfileHandlerResponseUserProfileMock()},]), undefined]), ...overrideResponse})


export const getGetUserProfileHandlerMockHandler = (overrideResponse?: UserProfileResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserProfileResponse> | UserProfileResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/user/profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserProfileHandlerResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUserMock = () => [
  getGetUserProfileHandlerMockHandler()
]
