/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export type CreateRoomRequestFormOneOfGameType = typeof CreateRoomRequestFormOneOfGameType[keyof typeof CreateRoomRequestFormOneOfGameType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoomRequestFormOneOfGameType = {
  baduk: 'baduk',
} as const;
