/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileResponseUser } from './userProfileResponseUser';

export interface UserProfileResponse {
  message: string;
  success: boolean;
  user?: UserProfileResponseUser;
}
