/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  GameResultInformationFrom,
  SessionCheckForm,
  UpdatePasswordForm,
  UpdateUsernameForm,
  UserProfileResponse
} from '../../model';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type deleteUserResponse200 = {
  data: ApiResponse
  status: 200
}

export type deleteUserResponse400 = {
  data: ApiResponse
  status: 400
}

export type deleteUserResponse500 = {
  data: ApiResponse
  status: 500
}

export type deleteUserResponseSuccess = (deleteUserResponse200) & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse400 | deleteUserResponse500) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseSuccess | deleteUserResponseError)

export const getDeleteUserUrl = () => {




  return `/api/user/delete`
}

export const deleteUser = async (sessionCheckForm: SessionCheckForm, options?: RequestInit): Promise<deleteUserResponse> => {

  return customInstance<deleteUserResponse>(getDeleteUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sessionCheckForm)
  }
);}





export const getDeleteUserQueryKey = (sessionCheckForm?: SessionCheckForm,) => {
    return [
    'POST', `/api/user/delete`, sessionCheckForm
    ] as const;
    }


export const getDeleteUserQueryOptions = <TData = Awaited<ReturnType<typeof deleteUser>>, TError = ApiResponse>(sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteUserQueryKey(sessionCheckForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteUser>>> = ({ signal }) => deleteUser(sessionCheckForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteUserQueryResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
export type DeleteUserQueryError = ApiResponse


export function useDeleteUser<TData = Awaited<ReturnType<typeof deleteUser>>, TError = ApiResponse>(
 sessionCheckForm: SessionCheckForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteUser>>,
          TError,
          Awaited<ReturnType<typeof deleteUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteUser<TData = Awaited<ReturnType<typeof deleteUser>>, TError = ApiResponse>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteUser>>,
          TError,
          Awaited<ReturnType<typeof deleteUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteUser<TData = Awaited<ReturnType<typeof deleteUser>>, TError = ApiResponse>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteUser<TData = Awaited<ReturnType<typeof deleteUser>>, TError = ApiResponse>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteUserQueryOptions(sessionCheckForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getGameResultResponse200 = {
  data: GameResultInformationFrom
  status: 200
}

export type getGameResultResponse400 = {
  data: void
  status: 400
}

export type getGameResultResponse404 = {
  data: void
  status: 404
}

export type getGameResultResponse500 = {
  data: void
  status: 500
}

export type getGameResultResponseSuccess = (getGameResultResponse200) & {
  headers: Headers;
};
export type getGameResultResponseError = (getGameResultResponse400 | getGameResultResponse404 | getGameResultResponse500) & {
  headers: Headers;
};

export type getGameResultResponse = (getGameResultResponseSuccess | getGameResultResponseError)

export const getGetGameResultUrl = (sessionKey: string,) => {




  return `/api/user/game_result_info/session/${sessionKey}`
}

export const getGameResult = async (sessionKey: string, options?: RequestInit): Promise<getGameResultResponse> => {

  return customInstance<getGameResultResponse>(getGetGameResultUrl(sessionKey),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGameResultQueryKey = (sessionKey: string,) => {
    return [
    `/api/user/game_result_info/session/${sessionKey}`
    ] as const;
    }


export const getGetGameResultQueryOptions = <TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameResultQueryKey(sessionKey);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameResult>>> = ({ signal }) => getGameResult(sessionKey, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: sessionKey !== null && sessionKey !== undefined,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameResultQueryResult = NonNullable<Awaited<ReturnType<typeof getGameResult>>>
export type GetGameResultQueryError = void


export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameResult>>,
          TError,
          Awaited<ReturnType<typeof getGameResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameResult>>,
          TError,
          Awaited<ReturnType<typeof getGameResult>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameResult<TData = Awaited<ReturnType<typeof getGameResult>>, TError = void>(
 sessionKey: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameResult>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameResultQueryOptions(sessionKey,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getUserProfileHandlerResponse200 = {
  data: UserProfileResponse
  status: 200
}

export type getUserProfileHandlerResponse404 = {
  data: UserProfileResponse
  status: 404
}

export type getUserProfileHandlerResponse500 = {
  data: UserProfileResponse
  status: 500
}

export type getUserProfileHandlerResponseSuccess = (getUserProfileHandlerResponse200) & {
  headers: Headers;
};
export type getUserProfileHandlerResponseError = (getUserProfileHandlerResponse404 | getUserProfileHandlerResponse500) & {
  headers: Headers;
};

export type getUserProfileHandlerResponse = (getUserProfileHandlerResponseSuccess | getUserProfileHandlerResponseError)

export const getGetUserProfileHandlerUrl = () => {




  return `/api/user/profile`
}

export const getUserProfileHandler = async (sessionCheckForm: SessionCheckForm, options?: RequestInit): Promise<getUserProfileHandlerResponse> => {

  return customInstance<getUserProfileHandlerResponse>(getGetUserProfileHandlerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sessionCheckForm)
  }
);}





export const getGetUserProfileHandlerQueryKey = (sessionCheckForm?: SessionCheckForm,) => {
    return [
    'POST', `/api/user/profile`, sessionCheckForm
    ] as const;
    }


export const getGetUserProfileHandlerQueryOptions = <TData = Awaited<ReturnType<typeof getUserProfileHandler>>, TError = UserProfileResponse>(sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProfileHandlerQueryKey(sessionCheckForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfileHandler>>> = ({ signal }) => getUserProfileHandler(sessionCheckForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProfileHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProfileHandler>>>
export type GetUserProfileHandlerQueryError = UserProfileResponse


export function useGetUserProfileHandler<TData = Awaited<ReturnType<typeof getUserProfileHandler>>, TError = UserProfileResponse>(
 sessionCheckForm: SessionCheckForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileHandler>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileHandler<TData = Awaited<ReturnType<typeof getUserProfileHandler>>, TError = UserProfileResponse>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileHandler>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileHandler<TData = Awaited<ReturnType<typeof getUserProfileHandler>>, TError = UserProfileResponse>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserProfileHandler<TData = Awaited<ReturnType<typeof getUserProfileHandler>>, TError = UserProfileResponse>(
 sessionCheckForm: SessionCheckForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileHandler>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProfileHandlerQueryOptions(sessionCheckForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updatePasswordResponse200 = {
  data: ApiResponse
  status: 200
}

export type updatePasswordResponse400 = {
  data: ApiResponse
  status: 400
}

export type updatePasswordResponse500 = {
  data: ApiResponse
  status: 500
}

export type updatePasswordResponseSuccess = (updatePasswordResponse200) & {
  headers: Headers;
};
export type updatePasswordResponseError = (updatePasswordResponse400 | updatePasswordResponse500) & {
  headers: Headers;
};

export type updatePasswordResponse = (updatePasswordResponseSuccess | updatePasswordResponseError)

export const getUpdatePasswordUrl = () => {




  return `/api/user/update-password`
}

export const updatePassword = async (updatePasswordForm: UpdatePasswordForm, options?: RequestInit): Promise<updatePasswordResponse> => {

  return customInstance<updatePasswordResponse>(getUpdatePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePasswordForm)
  }
);}





export const getUpdatePasswordQueryKey = (updatePasswordForm?: UpdatePasswordForm,) => {
    return [
    'POST', `/api/user/update-password`, updatePasswordForm
    ] as const;
    }


export const getUpdatePasswordQueryOptions = <TData = Awaited<ReturnType<typeof updatePassword>>, TError = ApiResponse>(updatePasswordForm: UpdatePasswordForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdatePasswordQueryKey(updatePasswordForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updatePassword>>> = ({ signal }) => updatePassword(updatePasswordForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updatePassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdatePasswordQueryResult = NonNullable<Awaited<ReturnType<typeof updatePassword>>>
export type UpdatePasswordQueryError = ApiResponse


export function useUpdatePassword<TData = Awaited<ReturnType<typeof updatePassword>>, TError = ApiResponse>(
 updatePasswordForm: UpdatePasswordForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updatePassword>>,
          TError,
          Awaited<ReturnType<typeof updatePassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdatePassword<TData = Awaited<ReturnType<typeof updatePassword>>, TError = ApiResponse>(
 updatePasswordForm: UpdatePasswordForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updatePassword>>,
          TError,
          Awaited<ReturnType<typeof updatePassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdatePassword<TData = Awaited<ReturnType<typeof updatePassword>>, TError = ApiResponse>(
 updatePasswordForm: UpdatePasswordForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUpdatePassword<TData = Awaited<ReturnType<typeof updatePassword>>, TError = ApiResponse>(
 updatePasswordForm: UpdatePasswordForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updatePassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdatePasswordQueryOptions(updatePasswordForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateUsernameResponse200 = {
  data: ApiResponse
  status: 200
}

export type updateUsernameResponse400 = {
  data: ApiResponse
  status: 400
}

export type updateUsernameResponse500 = {
  data: ApiResponse
  status: 500
}

export type updateUsernameResponseSuccess = (updateUsernameResponse200) & {
  headers: Headers;
};
export type updateUsernameResponseError = (updateUsernameResponse400 | updateUsernameResponse500) & {
  headers: Headers;
};

export type updateUsernameResponse = (updateUsernameResponseSuccess | updateUsernameResponseError)

export const getUpdateUsernameUrl = () => {




  return `/api/user/update-username`
}

export const updateUsername = async (updateUsernameForm: UpdateUsernameForm, options?: RequestInit): Promise<updateUsernameResponse> => {

  return customInstance<updateUsernameResponse>(getUpdateUsernameUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUsernameForm)
  }
);}





export const getUpdateUsernameQueryKey = (updateUsernameForm?: UpdateUsernameForm,) => {
    return [
    'POST', `/api/user/update-username`, updateUsernameForm
    ] as const;
    }


export const getUpdateUsernameQueryOptions = <TData = Awaited<ReturnType<typeof updateUsername>>, TError = ApiResponse>(updateUsernameForm: UpdateUsernameForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUsername>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateUsernameQueryKey(updateUsernameForm);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateUsername>>> = ({ signal }) => updateUsername(updateUsernameForm, { signal, ...requestOptions });





   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateUsername>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateUsernameQueryResult = NonNullable<Awaited<ReturnType<typeof updateUsername>>>
export type UpdateUsernameQueryError = ApiResponse


export function useUpdateUsername<TData = Awaited<ReturnType<typeof updateUsername>>, TError = ApiResponse>(
 updateUsernameForm: UpdateUsernameForm, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUsername>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateUsername>>,
          TError,
          Awaited<ReturnType<typeof updateUsername>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateUsername<TData = Awaited<ReturnType<typeof updateUsername>>, TError = ApiResponse>(
 updateUsernameForm: UpdateUsernameForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUsername>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateUsername>>,
          TError,
          Awaited<ReturnType<typeof updateUsername>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateUsername<TData = Awaited<ReturnType<typeof updateUsername>>, TError = ApiResponse>(
 updateUsernameForm: UpdateUsernameForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUsername>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUpdateUsername<TData = Awaited<ReturnType<typeof updateUsername>>, TError = ApiResponse>(
 updateUsernameForm: UpdateUsernameForm, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateUsername>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateUsernameQueryOptions(updateUsernameForm,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






