// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerToClient {
    #[prost(bool, tag = "1")]
    pub response_type: bool,
    #[prost(bool, optional, tag = "2")]
    pub running: ::core::option::Option<bool>,
    #[prost(enumeration = "GameType", tag = "3")]
    pub game_type: i32,
    #[prost(oneof = "server_to_client::GameData", tags = "101, 102")]
    pub game_data: ::core::option::Option<server_to_client::GameData>,
}
/// Nested message and enum types in `ServerToClient`.
pub mod server_to_client {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum GameData {
        #[prost(message, tag = "101")]
        Baduk(super::super::badukboard::BadukBoardServer),
        #[prost(message, tag = "102")]
        Omok(super::super::badukboard::BadukBoardServer),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientToServer {
    #[prost(oneof = "client_to_server::GameData", tags = "101, 102")]
    pub game_data: ::core::option::Option<client_to_server::GameData>,
}
/// Nested message and enum types in `ClientToServer`.
pub mod client_to_server {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum GameData {
        #[prost(message, tag = "101")]
        Baduk(super::super::badukboard::BadukBoardClient),
        #[prost(message, tag = "102")]
        Omok(super::super::badukboard::BadukBoardClient),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GameType {
    Unspecified = 0,
    Baduk = 1,
    Omok = 2,
}
impl GameType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "GAME_TYPE_UNSPECIFIED",
            Self::Baduk => "GAME_TYPE_BADUK",
            Self::Omok => "GAME_TYPE_OMOK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GAME_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "GAME_TYPE_BADUK" => Some(Self::Baduk),
            "GAME_TYPE_OMOK" => Some(Self::Omok),
            _ => None,
        }
    }
}
