// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.32.1
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BadukBoardClient, BadukBoardServer } from "./badukboard";

export const protobufPackage = "common";

export enum GameType {
  GAME_TYPE_UNSPECIFIED = 0,
  GAME_TYPE_BADUK = 1,
  GAME_TYPE_OMOK = 2,
  UNRECOGNIZED = -1,
}

export function gameTypeFromJSON(object: any): GameType {
  switch (object) {
    case 0:
    case "GAME_TYPE_UNSPECIFIED":
      return GameType.GAME_TYPE_UNSPECIFIED;
    case 1:
    case "GAME_TYPE_BADUK":
      return GameType.GAME_TYPE_BADUK;
    case 2:
    case "GAME_TYPE_OMOK":
      return GameType.GAME_TYPE_OMOK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GameType.UNRECOGNIZED;
  }
}

export function gameTypeToJSON(object: GameType): string {
  switch (object) {
    case GameType.GAME_TYPE_UNSPECIFIED:
      return "GAME_TYPE_UNSPECIFIED";
    case GameType.GAME_TYPE_BADUK:
      return "GAME_TYPE_BADUK";
    case GameType.GAME_TYPE_OMOK:
      return "GAME_TYPE_OMOK";
    case GameType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ServerToClient {
  responseType: boolean;
  running?: boolean | undefined;
  gameType: GameType;
  baduk?: BadukBoardServer | undefined;
  omok?: BadukBoardServer | undefined;
}

export interface ClientToServer {
  baduk?: BadukBoardClient | undefined;
  omok?: BadukBoardClient | undefined;
}

function createBaseServerToClient(): ServerToClient {
  return { responseType: false, running: undefined, gameType: 0, baduk: undefined, omok: undefined };
}

export const ServerToClient: MessageFns<ServerToClient> = {
  encode(message: ServerToClient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.responseType !== false) {
      writer.uint32(8).bool(message.responseType);
    }
    if (message.running !== undefined) {
      writer.uint32(16).bool(message.running);
    }
    if (message.gameType !== 0) {
      writer.uint32(24).int32(message.gameType);
    }
    if (message.baduk !== undefined) {
      BadukBoardServer.encode(message.baduk, writer.uint32(810).fork()).join();
    }
    if (message.omok !== undefined) {
      BadukBoardServer.encode(message.omok, writer.uint32(818).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerToClient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerToClient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.responseType = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.running = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.gameType = reader.int32() as any;
          continue;
        }
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.baduk = BadukBoardServer.decode(reader, reader.uint32());
          continue;
        }
        case 102: {
          if (tag !== 818) {
            break;
          }

          message.omok = BadukBoardServer.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerToClient {
    return {
      responseType: isSet(object.responseType)
        ? globalThis.Boolean(object.responseType)
        : isSet(object.response_type)
        ? globalThis.Boolean(object.response_type)
        : false,
      running: isSet(object.running) ? globalThis.Boolean(object.running) : undefined,
      gameType: isSet(object.gameType)
        ? gameTypeFromJSON(object.gameType)
        : isSet(object.game_type)
        ? gameTypeFromJSON(object.game_type)
        : 0,
      baduk: isSet(object.baduk) ? BadukBoardServer.fromJSON(object.baduk) : undefined,
      omok: isSet(object.omok) ? BadukBoardServer.fromJSON(object.omok) : undefined,
    };
  },

  toJSON(message: ServerToClient): unknown {
    const obj: any = {};
    if (message.responseType !== false) {
      obj.responseType = message.responseType;
    }
    if (message.running !== undefined) {
      obj.running = message.running;
    }
    if (message.gameType !== 0) {
      obj.gameType = gameTypeToJSON(message.gameType);
    }
    if (message.baduk !== undefined) {
      obj.baduk = BadukBoardServer.toJSON(message.baduk);
    }
    if (message.omok !== undefined) {
      obj.omok = BadukBoardServer.toJSON(message.omok);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerToClient>, I>>(base?: I): ServerToClient {
    return ServerToClient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerToClient>, I>>(object: I): ServerToClient {
    const message = createBaseServerToClient();
    message.responseType = object.responseType ?? false;
    message.running = object.running ?? undefined;
    message.gameType = object.gameType ?? 0;
    message.baduk = (object.baduk !== undefined && object.baduk !== null)
      ? BadukBoardServer.fromPartial(object.baduk)
      : undefined;
    message.omok = (object.omok !== undefined && object.omok !== null)
      ? BadukBoardServer.fromPartial(object.omok)
      : undefined;
    return message;
  },
};

function createBaseClientToServer(): ClientToServer {
  return { baduk: undefined, omok: undefined };
}

export const ClientToServer: MessageFns<ClientToServer> = {
  encode(message: ClientToServer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baduk !== undefined) {
      BadukBoardClient.encode(message.baduk, writer.uint32(810).fork()).join();
    }
    if (message.omok !== undefined) {
      BadukBoardClient.encode(message.omok, writer.uint32(818).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientToServer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientToServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.baduk = BadukBoardClient.decode(reader, reader.uint32());
          continue;
        }
        case 102: {
          if (tag !== 818) {
            break;
          }

          message.omok = BadukBoardClient.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientToServer {
    return {
      baduk: isSet(object.baduk) ? BadukBoardClient.fromJSON(object.baduk) : undefined,
      omok: isSet(object.omok) ? BadukBoardClient.fromJSON(object.omok) : undefined,
    };
  },

  toJSON(message: ClientToServer): unknown {
    const obj: any = {};
    if (message.baduk !== undefined) {
      obj.baduk = BadukBoardClient.toJSON(message.baduk);
    }
    if (message.omok !== undefined) {
      obj.omok = BadukBoardClient.toJSON(message.omok);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientToServer>, I>>(base?: I): ClientToServer {
    return ClientToServer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientToServer>, I>>(object: I): ClientToServer {
    const message = createBaseClientToServer();
    message.baduk = (object.baduk !== undefined && object.baduk !== null)
      ? BadukBoardClient.fromPartial(object.baduk)
      : undefined;
    message.omok = (object.omok !== undefined && object.omok !== null)
      ? BadukBoardClient.fromPartial(object.omok)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
