/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type swaggerUiPageResponse200 = {
  data: void
  status: 200
}

export type swaggerUiPageResponseSuccess = (swaggerUiPageResponse200) & {
  headers: Headers;
};
;

export type swaggerUiPageResponse = (swaggerUiPageResponseSuccess)

export const getSwaggerUiPageUrl = () => {


  

  return `/api/admin/openapi`
}

export const swaggerUiPage = async ( options?: RequestInit): Promise<swaggerUiPageResponse> => {
  
  return customInstance<swaggerUiPageResponse>(getSwaggerUiPageUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getSwaggerUiPageQueryKey = () => {
    return [
    `/api/admin/openapi`
    ] as const;
    }

    
export const getSwaggerUiPageQueryOptions = <TData = Awaited<ReturnType<typeof swaggerUiPage>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof swaggerUiPage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSwaggerUiPageQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof swaggerUiPage>>> = ({ signal }) => swaggerUiPage({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof swaggerUiPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SwaggerUiPageQueryResult = NonNullable<Awaited<ReturnType<typeof swaggerUiPage>>>
export type SwaggerUiPageQueryError = unknown


export function useSwaggerUiPage<TData = Awaited<ReturnType<typeof swaggerUiPage>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof swaggerUiPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof swaggerUiPage>>,
          TError,
          Awaited<ReturnType<typeof swaggerUiPage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSwaggerUiPage<TData = Awaited<ReturnType<typeof swaggerUiPage>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof swaggerUiPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof swaggerUiPage>>,
          TError,
          Awaited<ReturnType<typeof swaggerUiPage>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSwaggerUiPage<TData = Awaited<ReturnType<typeof swaggerUiPage>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof swaggerUiPage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSwaggerUiPage<TData = Awaited<ReturnType<typeof swaggerUiPage>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof swaggerUiPage>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSwaggerUiPageQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary OpenAPI JSON 스펙을 반환하는 엔드포인트
 */
export type getOpenapiSpecResponse200 = {
  data: void
  status: 200
}

export type getOpenapiSpecResponse500 = {
  data: void
  status: 500
}

export type getOpenapiSpecResponseSuccess = (getOpenapiSpecResponse200) & {
  headers: Headers;
};
export type getOpenapiSpecResponseError = (getOpenapiSpecResponse500) & {
  headers: Headers;
};

export type getOpenapiSpecResponse = (getOpenapiSpecResponseSuccess | getOpenapiSpecResponseError)

export const getGetOpenapiSpecUrl = () => {


  

  return `/api/admin/openapi/openapi.json`
}

export const getOpenapiSpec = async ( options?: RequestInit): Promise<getOpenapiSpecResponse> => {
  
  return customInstance<getOpenapiSpecResponse>(getGetOpenapiSpecUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetOpenapiSpecQueryKey = () => {
    return [
    `/api/admin/openapi/openapi.json`
    ] as const;
    }

    
export const getGetOpenapiSpecQueryOptions = <TData = Awaited<ReturnType<typeof getOpenapiSpec>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenapiSpec>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOpenapiSpecQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOpenapiSpec>>> = ({ signal }) => getOpenapiSpec({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOpenapiSpec>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOpenapiSpecQueryResult = NonNullable<Awaited<ReturnType<typeof getOpenapiSpec>>>
export type GetOpenapiSpecQueryError = void


export function useGetOpenapiSpec<TData = Awaited<ReturnType<typeof getOpenapiSpec>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenapiSpec>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpenapiSpec>>,
          TError,
          Awaited<ReturnType<typeof getOpenapiSpec>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpenapiSpec<TData = Awaited<ReturnType<typeof getOpenapiSpec>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenapiSpec>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOpenapiSpec>>,
          TError,
          Awaited<ReturnType<typeof getOpenapiSpec>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOpenapiSpec<TData = Awaited<ReturnType<typeof getOpenapiSpec>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenapiSpec>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary OpenAPI JSON 스펙을 반환하는 엔드포인트
 */

export function useGetOpenapiSpec<TData = Awaited<ReturnType<typeof getOpenapiSpec>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOpenapiSpec>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOpenapiSpecQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




