/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePasswordForm {
  current_password: string;
  new_password: string;
  session_key: string;
}
