/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * doljabi
 * doljabi project REST API를 정의한 문서입니다.
 * OpenAPI spec version: 1.0.0
 */

export interface LoginForm {
  /** 로그인에 사용할 아이디 */
  login_id: string;
  /** 평문 비밀번호 */
  password: string;
}
